import { C, S, PAGE, getScoreColor, getScoreLight } from "./constants";
import { fc, sc, hline, safeDate } from "./helpers";
import { scoreBadge, confidentialTag } from "./components/badges";
import { trackingLabel } from "./components/typography";
import { AssessmentDocument } from "../../types/assessment";

export function renderCover(
  doc: PDFKit.PDFDocument,
  document: AssessmentDocument,
  logoBuffer: Buffer | null
) {
  const { width: PW, height: PH, margin: M, contentWidth: CW } = PAGE;
  const report = document.report.data!;
  const score  = report.readinessScore.total;

  // White background
  fc(doc, C.white);
  doc.rect(0, 0, PW, PH).fill();

  // Left accent bar
  fc(doc, C.primary);
  doc.rect(0, 0, 6, PH).fill();

  // Top bg strip
  fc(doc, C.bg);
  doc.rect(6, 0, PW - 6, 90).fill();
  hline(doc, 6, 90, PW - 6, C.border);

  // Decorative circles bottom-right
  doc.save();
  doc.fillOpacity(0.04);
  fc(doc, C.primary);
  doc.circle(PW - 50, PH - 100, 160).fill();
  doc.circle(PW - 20, PH - 280, 90).fill();
  doc.restore();

  // Logo
  if (logoBuffer) {
    doc.image(logoBuffer, M, 28, { width: 140 });
  } else {
    fc(doc, C.primary);
    doc.font("Helvetica-Bold").fontSize(18).text("KlayyTech", M, 34);
  }

  // Report type
  trackingLabel(doc, M, 112, "CLOUD READINESS ASSESSMENT REPORT");

  // Title
  fc(doc, C.text);
  doc.font("Helvetica-Bold").fontSize(34).text("Cloud Readiness", M, 130);
  doc.font("Helvetica-Bold").fontSize(34).text("Assessment",      M, 170);

  // Score badge
  scoreBadge(
    doc, M, 222, score,
    report.readinessScore.level,
    getScoreLight(score),
    getScoreColor(score)
  );

  hline(doc, M, 280, CW, C.border);

  // Prepared for
  trackingLabel(doc, M, 298, "PREPARED FOR");
  fc(doc, C.text);
  doc.font("Helvetica-Bold").fontSize(24).text(document.companyName, M, 314);
  fc(doc, C.textSec);
  doc.font("Helvetica").fontSize(10)
    .text(
      `${report.companyOverview.industry} · ${report.companyOverview.companySize} employees`,
      M, 344
    );

  hline(doc, M, 372, CW, C.border);

  // Prepared by
  trackingLabel(doc, M, 390, "PREPARED BY");
  fc(doc, C.text);
  doc.font("Helvetica-Bold").fontSize(14).text("KlayyTech Cloud Solutions Team", M, 406);
  fc(doc, C.textSec);
  doc.font("Helvetica").fontSize(9).text("support@klayytech.com", M, 424);

  hline(doc, M, 452, CW, C.border);

  // Meta columns
  const meta = [
    { label: "REPORT ID",     value: document.id },
    { label: "GENERATED",     value: safeDate(document.meta.generatedAt) },
    { label: "AI CONFIDENCE", value: `${document.meta.confidenceScore ?? 82}%` },
  ];
  meta.forEach((col, i) => {
    const cx = M + i * (CW / 3);
    trackingLabel(doc, cx, 470, col.label);
    fc(doc, C.text);
    doc.font("Helvetica-Bold").fontSize(10).text(col.value, cx, 484);
  });

  // CONFIDENTIAL tag
  confidentialTag(doc, M, PH - 66);

  // Footer line
  fc(doc, C.textTer);
  doc.font("Helvetica").fontSize(7.5)
    .text(
      "Generated by KlayyTech CloudReady · Powered by Azure OpenAI",
      M, PH - 30, { width: CW, align: "center" }
    );
}